### ISSUE TITLE
Bonjour!

### ISSUE THREAD

**Issue by Doubledom45** [crazymikefra/HA_RFPlayerNext#1]
Peut-on travailler sur ton projet Rfplayer ?
Je vois que tu as repris et fais pas mal de modification sur le projet en cours.
Une petite question pourquoi pas de demande de Pull requests sur l'original.

Pour info mon Pseudo sur HA fr Doubledom si tu veux me contacter.

PS je vais essayer ta version si cela ne te gène pas ?![bitmoji](https://sdk.bitmoji.com/render/panel/9d438724-a1e5-44b9-9172-377503bbffe6-2d67f77a-6c59-4c00-829b-9ae71d5c2ae1-v1.png?transparent=1&palette=1&width=246)

**Comment by crazymikefra** [comment]
Bonjour @Doubledom45 .
Pas de soucis pour travailler sur ma version.

Je n'ai pas fait de Pull Request sur l'original car ;
- Je suis parti de la version officielle que j'ai aménagé et stabilisé pour déjà avoir une couverture d'au moins 90% de l'API, au moins sur le format JSON.
- Du fait que j'ai modifié beaucoup de choses en profondeur et que j'ai désactivé du code, il n'est pas rétro-compatible avec la version officielle
- Le but de cette version est de partir de ma version stabilisée et de se baser sur les standard Home Assistant comme détaillé dans leur doc de DEV.

Pour cette nouvelle version, je n'ai mis en place que mon étude des API.
Par contre, pour une version, fonctionnelle en l'état, située entre la version standard et cette nouvelle, il faut regarder sur mon autre dépot : [https://github.com/crazymikefra/HA_RFPlayer](https://github.com/crazymikefra/HA_RFPlayer)

J'ai changé de taf il y a quelques temps et je profite de ce projet pour me remettre à niveau.
Par contre, je fais de bonne journée et je risque de moins pouvoir fournir dans les semaines qui viennent.

Tu peux donc essayer cette nouvelle version et celle de mon autre dépot sans soucis.

N'hésite pas à revenir vers moi au besoin.

**Comment by Doubledom45** [comment]
Slt..
J'ai testé la version sur  [ https://github.com/crazymikefra/HA_RFPlayer](https://github.com/crazymikefra/HA_RFPlayer)
Est-ce que toi tu as testé ?

Mois bug, doit y avoir un problème lors de la vérification protocol , il y a systématiquement : 
`ERROR (MainThread) [custom_components.rfplayer.rflib.rfpparser] Protocol OREGON not implemented : unhashable type: 'dict'
DEBUG (MainThread) [custom_components.rfplayer.rflib.rfpparser] Trace : Traceback (most recent call last):`
Quelque soit le protocol , l'infoType_x est bien vue ici infoType_4 pour **_Oregon ainsi que OWL EDISIO CHACON_** pour ceux que j'ai essayé !

> 
```
2023-02-26 13:35:57.485 WARNING (MainThread) [custom_components.rfplayer.rflib.rfpprotocol] no valid packet
2023-02-26 13:35:59.356 ERROR (MainThread) [custom_components.rfplayer.rflib.rfpparser] Protocol OREGON not implemented : unhashable type: 'dict'
2023-02-26 13:35:59.357 DEBUG (MainThread) [custom_components.rfplayer.rflib.rfpparser] Trace : Traceback (most recent call last):
  File "/config/custom_components/rfplayer/rflib/rfpparser.py", line 137, in decode_packet
    packets_found.append(globals()["_".join([data["protocol"],"decode"])](data,message,PacketHeader.gateway.name))
  File "/config/custom_components/rfplayer/rflib/protocols.py", line 162, in OREGON_decode
    decoding=globals()["_".join(["infoType",decoded_items["infoType"],"decode"])](message['infos'])
  File "/config/custom_components/rfplayer/rflib/infotypes.py", line 143, in infoType_4_decode
    if elements[measure] != '':
TypeError: unhashable type: 'dict'

2023-02-26 13:35:59.357 WARNING (MainThread) [custom_components.rfplayer.rflib.rfpprotocol] no valid packet
2023-02-26 13:35:00.346 ERROR (MainThread) [custom_components.rfplayer.rflib.rfpparser] Protocol OWL not implemented : unhashable type: 'dict'
2023-02-26 13:35:00.348 DEBUG (MainThread) [custom_components.rfplayer.rflib.rfpparser] Trace : Traceback (most recent call last):
  File "/config/custom_components/rfplayer/rflib/rfpparser.py", line 137, in decode_packet
    packets_found.append(globals()["_".join([data["protocol"],"decode"])](data,message,PacketHeader.gateway.name))
  File "/config/custom_components/rfplayer/rflib/protocols.py", line 204, in OWL_decode
    decoding=globals()["_".join(["infoType",decoded_items["infoType"],"decode"])](message['infos'])
  File "/config/custom_components/rfplayer/rflib/infotypes.py", line 262, in infoType_8_decode
    if elements[measure] != '':
TypeError: unhashable type: 'dict'

2023-02-26 13:35:00.348 WARNING (MainThread) [custom_components.rfplayer.rflib.rfpprotocol] no valid packet
2023-02-26 13:35:01.029 ERROR (MainThread) [custom_components.rfplayer.rflib.rfpparser] Protocol EDISIO not implemented : 'infoType_15_decode'
2023-02-26 13:35:01.030 DEBUG (MainThread) [custom_components.rfplayer.rflib.rfpparser] Trace : Traceback (most recent call last):
  File "/config/custom_components/rfplayer/rflib/rfpparser.py", line 137, in decode_packet
    packets_found.append(globals()["_".join([data["protocol"],"decode"])](data,message,PacketHeader.gateway.name))
  File "/config/custom_components/rfplayer/rflib/protocols.py", line 383, in EDISIO_decode
    decoding=globals()["_".join(["infoType",decoded_items["infoType"],"decode"])](message['infos'])
KeyError: 'infoType_15_decode'

2023-02-26 13:35:01.030 WARNING (MainThread) [custom_components.rfplayer.rflib.rfpprotocol] no valid packet
2023-02-26 13:35:05.993 ERROR (MainThread) [custom_components.rfplayer.rflib.rfpparser] Protocol EDISIO not implemented : 'infoType_15_decode'
2023-02-26 13:35:05.994 DEBUG (MainThread) [custom_components.rfplayer.rflib.rfpparser] Trace : Traceback (most recent call last):
  File "/config/custom_components/rfplayer/rflib/rfpparser.py", line 137, in decode_packet
    packets_found.append(globals()["_".join([data["protocol"],"decode"])](data,message,PacketHeader.gateway.name))
  File "/config/custom_components/rfplayer/rflib/protocols.py", line 383, in EDISIO_decode
    decoding=globals()["_".join(["infoType",decoded_items["infoType"],"decode"])](message['infos'])
KeyError: 'infoType_15_decode'

2023-02-26 13:35:05.994 WARNING (MainThread) [custom_components.rfplayer.rflib.rfpprotocol] no valid packet

2023-02-26 13:56:07.391 ERROR (MainThread) [custom_components.rfplayer.rflib.rfpparser] Protocol CHACON not implemented : 'subType'
2023-02-26 13:56:07.392 DEBUG (MainThread) [custom_components.rfplayer.rflib.rfpparser] Trace : Traceback (most recent call last):
  File "/config/custom_components/rfplayer/rflib/rfpparser.py", line 137, in decode_packet
    packets_found.append(globals()["_".join([data["protocol"],"decode"])](data,message,PacketHeader.gateway.name))
  File "/config/custom_components/rfplayer/rflib/protocols.py", line 141, in CHACON_decode
    decoding=globals()["_".join(["infoType",decoded_items["infoType"],"decode"])](message['infos'])
  File "/config/custom_components/rfplayer/rflib/infotypes.py", line 66, in infoType_1_decode
    fields_found["command"]=fields_found["subType"]
KeyError: 'subType'

2023-02-26 13:56:07.393 WARNING (MainThread) [custom_components.rfplayer.rflib.rfpprotocol] no valid packet
```
J'ai vu que tu n'as pas initier le Jamming ?

>
```
2023-02-26 13:36:13.712 ERROR (MainThread) [custom_components.rfplayer.rflib.rfpparser] Protocol JAMMING not implemented : 'subType'
2023-02-26 13:36:13.724 DEBUG (MainThread) [custom_components.rfplayer.rflib.rfpparser] Trace : Traceback (most recent call last):
  File "/config/custom_components/rfplayer/rflib/rfpparser.py", line 137, in decode_packet
    packets_found.append(globals()["_".join([data["protocol"],"decode"])](data,message,PacketHeader.gateway.name))
  File "/config/custom_components/rfplayer/rflib/protocols.py", line 362, in JAMMING_decode
    decoding=globals()["_".join(["infoType",decoded_items["infoType"],"decode"])](message['infos'])
  File "/config/custom_components/rfplayer/rflib/infotypes.py", line 66, in infoType_1_decode
    fields_found["command"]=fields_found["subType"]
KeyError: 'subType'

2023-02-26 13:36:13.724 WARNING (MainThread) [custom_components.rfplayer.rflib.rfpprotocol] no valid packet
```
L'erreur doit venir de ton "rfpparser" ?
```
    NewMotor=False


    try:
        packets_found.append(globals()["_".join([data["protocol"],"decode"])](data,message,PacketHeader.gateway.name))
        NewMotor=True
    except Exception as e:
        log.error("Protocol %s not implemented : %s", str(data["protocol"]),str(e))
        log.debug("Trace : %s",traceback.format_exc())
        #log.debug("Message : %s", str(message))

    #if packets_found==[None]:
    #    log.error("No packets found in %s", str(message))
    #log.debug("Packets Found : %s", str(packets_found))
    return packets_found
```
D'autres **_erreurs_** surement sur OWL il doit manquer l'éléments energy ?, j'ai pas poussé plus le décodage d'autres mais je crois que sur EDISIO ne va pas non plus ? mais facilement modifiables du coup ....
La façon d'initialisé le Rfplayer à aussi une erreur dans rfpprotocol ( mais pas contraignante)
```
 def connection_made(self, transport: asyncio.BaseTransport) -> None:
        """Just logging for now.""" 
        self.transport = transport
        #log.debug("connected")
        self.send_raw_packet("ZIA++HELLO")
        self.send_raw_packet("ZIA++RECEIVER + *")
         #Voir utilisation de FACTORYRESET au lieu des réglages de base, SENSITITY L/H ?
        self.send_raw_packet("ZIA++SENSITIVITY L 6") #("ZIA++SENSITIVITY L 0") ?
        self.send_raw_packet("ZIA++SENSITIVITY H 8") #("ZIA++SENSITIVITY H 0") ?
        self.send_raw_packet("ZIA++SELECTIVITY L 0") #("ZIA++SELECTIVITY L 8") ?
        self.send_raw_packet("ZIA++SELECTIVITY H 0") #("ZIA++SELECTIVITY H 6") ?
        self.send_raw_packet("ZIA++RFLINK 1")
        self.send_raw_packet("ZIA++RFLINKTRIGGER L 12")
        self.send_raw_packet("ZIA++RFLINKTRIGGER H 10")
        self.send_raw_packet("ZIA++LBT 16")
        self.send_raw_packet("ZIA++FORMAT JSON")
        self.send_raw_packet("ZIA++STATUS")
        #log.debug("initialized")
```

Pour la suite de nos échanges serait-il possible d'ouvrir un fil de discussion ![image](https://user-images.githubusercontent.com/97252459/221416211-bfefc904-74ef-4273-8294-71411ed89649.png)
 Ou sur email directement
Bien à toi ![bitmoji](https://sdk.bitmoji.com/render/panel/5b7bff30-d7cc-4141-9f91-d77fa135057f-2d67f77a-6c59-4c00-829b-9ae71d5c2ae1-v1.png?transparent=1&palette=1&width=246)

**Comment by crazymikefra** [comment]
Salut.

La version Next n'est pas opérationnelle mais cela m'étonne sur le forum
car c'est la version que j'utilise sur mon installation.

A en rediscuter.

**Comment by crazymikefra** [comment]
Pour les soucis de décodage, normalement je met aussi les trames en débogage. Je veux bien que tu m'en passe pour que je vois où ça coince même si j'ai ma petite idée ;-) 
De mon côté, j'ai essentiellement pu tester du RTS, de l'OREGON, du VISONIC et du X2D.
Pour les autres protocoles, j'ai extrapolé par rapport à ce que j'avais observé ainsi que la doc de l'API.

**Comment by Doubledom45** [comment]
Ok voici ce que j'ai pu avoir avec le prog du Rfplayer ( tu as tes infos plus haut)
[log.txt](https://github.com/crazymikefra/HA_RFPlayerNext/files/10834125/log.txt)

Si tu veux je peut aussi voir le log de ma version sur HA

**Comment by crazymikefra** [comment]
Arf !
J'avais pas envoyé mes dernières modifs visiblement lol.
Je viens de faire le push.

**Comment by Doubledom45** [comment]
Ok je continue la discussion sur ![image](https://user-images.githubusercontent.com/97252459/221425297-8825832f-5c8e-4b27-a99d-2025cda02a43.png)
